name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        env:
            GRPC_VERSION: v1.37.x
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.x'
            -   name: Install build dependecies
                run: apt update && apt-get install -y build-essential autoconf libtool pkg-config cmake
            -   name: Clone grpc repo
                uses: actions/checkout@v2
                with:
                    repository: "grpc/grpc"
                    path: tmp/grpc
                    ref: ${{ env.GRPC_VERSION }}
                    submodules: recursive
            -   name: Build grpc_php_plugin
                working-directory: tmp/grpc
                run: |
                    mkdir -p cmake/build
                    cd cmake/build
                    cmake ../..
                    make protoc
                    make grpc_php_plugin
            -   name: Copy gRPC files to project dir
                working-directory: tmp/grpc
                run: |
                    cp cmake/build/grpc_php_plugin ../../src/Sitko.Grpc.Tools.Php/Tools/grpc_php_plugin
                    cp cmake/build/third_party/protobuf/protoc ../../src/Sitko.Grpc.Tools.Php/Tools/protoc
                    mkdir -p ../../src/Sitko.Grpc.Tools.Php/Proto/google/protobuf
                    cp third_party/protobuf/src/google/protobuf/*.proto ../../src/Sitko.Grpc.Tools.Php/Proto/google/protobuf
            -   name: Create package
                run: dotnet pack -c Release
